import { Poppins } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Web3ModalProvider from "@/context/web3modal";
import { config } from "@/config";
import { cookieToInitialState } from "wagmi";
import { headers } from 'next/headers';

const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] });

export const metadata = {
  title: "NexaFundify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
        <body className={poppins.className}>
        <ChakraProvider>
          <Web3ModalProvider initialState={initialState}>{children}</Web3ModalProvider>
        </ChakraProvider>
        </body>
    </html>
  );
}
